# Generated by Django 5.0.1 on 2024-01-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("optional", "Optional"),
                            ("required", "Required"),
                            ("hidden", "Hidden"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "email_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("optional", "Optional"),
                            ("required", "Required"),
                            ("hidden", "Hidden"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "password_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("optional", "Optional"),
                            ("required", "Required"),
                            ("hidden", "Hidden"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "password2_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("optional", "Optional"),
                            ("required", "Required"),
                            ("hidden", "Hidden"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "first_name_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("optional", "Optional"),
                            ("required", "Required"),
                            ("hidden", "Hidden"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "last_name_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("optional", "Optional"),
                            ("required", "Required"),
                            ("hidden", "Hidden"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "mobile_number_option",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("optional", "Optional"),
                            ("required", "Required"),
                            ("hidden", "Hidden"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
